server.port=${SERVER_PORT:8080}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=ms-cliente-route
spring.cloud.gateway.routes[0].uri=lb://ms-cliente
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clientes/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/clientes/(?<segment>.*), /clientes/${segment}

spring.cloud.gateway.routes[1].id=ms-producto-route
spring.cloud.gateway.routes[1].uri=lb://ms-producto
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/productos/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/productos/(?<segment>.*), /productos/${segment}

spring.cloud.gateway.routes[2].id=ms-ventas-route
spring.cloud.gateway.routes[2].uri=lb://ms-ventas
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/ventas/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/ventas/(?<segment>.*), /ventas/${segment}

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

management.endpoints.web.exposure.include=health,info,gateway
